### ISSUE TITLE
I2C error after soft reboot

### ISSUE THREAD

**Issue by BrianPugh** [adafruit/Adafruit_CircuitPython_VEML7700#14]
I am having a very similar issue outlined in this issue:
https://github.com/adafruit/circuitpython/issues/2060

Essentially, I am able to communicate with the VEML7700 on first boot from my nRF52840, but subsequent soft reboots (such as during code reloads) cause the traceback as follows:

```
>>> veml7700 = adafruit_veml7700.VEML7700(i2c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_veml7700.py", line 207, in __init__
  File "adafruit_register/i2c_bit.py", line 70, in __set__
  File "adafruit_register/i2c_bit.py", line 65, in __set__
  File "adafruit_bus_device/i2c_device.py", line 143, in write_then_readinto
OSError: [Errno 19] Unsupported operation
```

Through experimentation, I have found that this can be mitigated  by replacing this line:

https://github.com/adafruit/Adafruit_CircuitPython_VEML7700/blob/f57ccd9e9f24e56007b5f99ceece67e83cc305ac/adafruit_veml7700.py#L206

with:

```
try:
    self.light_shutdown = False
except OSError:
    self.light_shutdown = False
```

On a cold boot, the first `self.light_shutdown = False` works successfully. On subsequent soft reboots, it will fail with the traceback previously mentioned; however, running the command again always works. I guess maybe the first attempt flushs some buffer or fixes some invalid state?

I can make a PR if convenient, but just checking if this maybe is just a symptom of an upstream bug that should be fixed instead.

**Comment by ladyada** [comment]
hi idea is good! for implementation i think better to perhaps have a loop where it tries 3 times to enable, and if it does not enable (`else:` at the end of the for loop) it throws a runtime error

**Comment by BrianPugh** [comment]
cool! I'll make a PR soon with this change

**Comment by BrianPugh** [comment]
bump

**Comment by BrianPugh** [comment]
closing since PR15 has been merged

**Comment by jposada202020** [comment]
@BrianPugh Thanks :)
