### ISSUE TITLE
KeyError 4 getting lux value

### ISSUE THREAD

**Issue by RobCranfill** [adafruit/Adafruit_CircuitPython_VEML7700#18]
The following code, a very slight modification of the standard test code, fails:

	import time
	import board
	import adafruit_veml7700
	
	i2c = board.I2C()  # uses board.SCL and board.SDA
	veml7700 = adafruit_veml7700.VEML7700(i2c)
	
	while True:
	    # print("Ambient light:", veml7700.light) # this works
	    print("Ambient light:", veml7700.lux) # this does not
	    time.sleep(1.0)

The failure is this:

	Traceback (most recent call last):
	  File "v1.py", line 10, in <module>
	    print("Ambient light:", veml7700.lux)
	  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_veml7700.py", line 239, in lux
	    return self.resolution() * self.light
	  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_veml7700.py", line 216, in resolution
	    * (gain_max / self.gain_value())
	  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_veml7700.py", line 194, in integration_time_value
	    return self.integration_time_values[integration_time]
	KeyError: 4

**Comment by RobCranfill** [comment]
Oho! So I tried *setting* the integration time to zero, and guess what? It
works (or at any rate it doesn't throw an exception)

>>> veml.light_integration_time = 0
>>> veml.lux
38.7072

I will try this in my project. (I have an RPi driving an LCD display that
shows output from my weather station; the light sensor automatically
adjusts the LCDs backlight so it's not too bright at night. See
https://github.com/RobCranfill/blatb if you care. ;-)

Thanks for your help!

</rob>

**Comment by caternuson** [comment]
Yes, getting a `4` would be an issue. That is not a valid setting, which is what is throwing the key error. `0` is a valid setting. The valid settings are:
```python
    ALS_25MS = const(0xC)
    ALS_50MS = const(0x8)
    ALS_100MS = const(0x0)
    ALS_200MS = const(0x1)
    ALS_400MS = const(0x2)
    ALS_800MS = const(0x3)
```

So the question is how it got set to `4` in the first place? Were you doing that?

**Comment by RobCranfill** [comment]
I had this exception crop up again. I do seem to be able to fix it (I thought I had already done this, but apparently not) by doing:

```
  veml7700 = adafruit_veml7700.VEML7700(i2c)

  # prevent key error? (is this the best way?)
  #     File "/home/pi/.local/lib/python3.7/site-packages/adafruit_veml7700.py", line 194, in integration_time_value
  #       return self.integration_time_values[integration_time]
  #   KeyError: 6
  veml7700.light_integration_time = veml7700.ALS_100MS

```
