### ISSUE TITLE
Parameter settings of integration time may be wrong.

### ISSUE THREAD

**Issue by ssagat** [adafruit/Adafruit_CircuitPython_VEML7700#6]
From "Designing the VEML7700 Into an Application"(https://www.vishay.com/docs/84323/designingveml7700.pdf), 

REGISTER NAME BIT FUNCTION / DESCRIPTION R / W
ALS_IT 9 : 6
ALS integration time setting
1100 = 25 ms
1000 = 50 ms
0000 = 100 ms
0001 = 200 ms
0010 = 400 ms
0011 = 800 ms

So, I think the parameters of integration time settings should be,
    ALS_25MS = const(0xC)
    ALS_50MS = const(0x8)
    ALS_100MS = const(0x0)
    ALS_200MS = const(0x1)
    ALS_400MS = const(0x2)
    ALS_800MS = const(0x3)

Because of the current wrong parameter settings, both "light" and "lux" values are different from other sample codes.

**Comment by siddacious** [comment]
Thanks @ssagat you were indeed correct. The datasheet isn't the clearest!
