### ISSUE TITLE
TypeError: integer is required

### ISSUE THREAD

**Issue by hojunson** [adafruit/Adafruit_CircuitPython_VEML7700#8]
I am using Jetson nano and Circuitpython. 
Actually it was working but after updating Jetson kernel, I got this error
![image](https://user-images.githubusercontent.com/24233353/71393871-b18c0d80-25dc-11ea-85c2-10d6c85109fb.png)

Do you have any idea?

Thanks.

**Comment by kattni** [comment]
@hojunson Are you still experiencing this issue?

**Comment by hojunson** [comment]
No It is okay.

2020년 5월 4일 (월) 오전 10:42, Kattni <notifications@github.com>님이 작성:

**Comment by kattni** [comment]
Thank you! Closing.
